brace_style = "PreferSameLine"
force_multiline_blocks = "true"
format_code_in_doc_comments = "true"
format_generated_files = "false"
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
max_width = "80"
merge_imports = "true"
newline_style = "Unix"
normalize_doc_attributes = "true"
overflow_delimited_expr = "true"
reorder_impl_items = "true"
tab_spaces = 2
unstable_features = "true"
use_field_init_shorthand = "true"
use_try_shorthand = "true"
version = "Two"
where_single_line = "true"
