[package]
name = "utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strum = { version = "0.24", features = ["derive"] }
mongodb = "2.2.1"
json5 = "0.4.1"
serde_json = "1.0.81"
base64 = "0.13.0"
time = "0.3.9"
uuid = "1.1.0"
